# config.yaml
input_dir: "/home/hellern/isilon/data/weaver_projects/request_176"
manifest_path: "/home/hellern/isilon/data/weaver_projects/request_176_accession_map.csv"
output_base_dir: "/home/hellern/isilon/data/weaver_projects/request_176_deid_v2_demo"
csv_output_manifest: "/home/hellern/isilon/data/weaver_projects/request_176_deid_log_demo.csv"
redaction_mode: "Smart"
